# Generated by Django 4.0.6 on 2022-11-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.highlight')),
            ],
        ),
    ]
