# Generated by Django 4.0.6 on 2022-11-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_thought'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.TextField()),
            ],
        ),
    ]
