# Generated by Django 4.0.6 on 2022-11-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_temp_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp_note',
        ),
        migrations.AddField(
            model_name='highlight',
            name='thought',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Thought',
        ),
    ]
